# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4757eeee0a8ff8bc342fb29f76c628b84f63d544f38d695ee221612c74048f99638f7f7640e04d58349684254ab361b23211b53a3a32c54d562907d80898945a

test:
  secret_key_base: d2186200cae621c35131b57e864c6469b65b0bb5311e3d93af90bc33f05e302c63f19e3813dfb6cfb835f2938e8e4415616467dd0ffc92d621b176e88b220c31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
